# Generated by Django 3.2.6 on 2021-08-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('usuario', models.CharField(max_length=25, verbose_name='nombre usuario')),
                ('creado', models.DateField(auto_now_add=True, verbose_name='fecha creación de usuario')),
            ],
        ),
    ]
