# Generated by Django 3.2.6 on 2021-08-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_auto_20210810_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='example@tumail.com', max_length=254),
            preserve_default=False,
        ),
    ]
