# Generated by Django 3.2.6 on 2021-08-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0004_auto_20210810_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=12, verbose_name='contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='creado',
            field=models.DateField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=25, verbose_name='usuario'),
        ),
    ]
