# Generated by Django 3.2.6 on 2021-08-14 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0005_auto_20210810_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_name', models.CharField(max_length=50)),
                ('pregunta_number', models.PositiveIntegerField()),
                ('total_marcas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=600)),
                ('opcion1', models.CharField(max_length=200)),
                ('opcion2', models.CharField(max_length=200)),
                ('opcion3', models.CharField(max_length=200)),
                ('opcion4', models.CharField(max_length=200)),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.pregunta')),
            ],
        ),
    ]
