# Generated by Django 3.2.6 on 2021-08-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0006_pregunta_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='respuesta',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
