# Generated by Django 3.2.6 on 2021-08-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0008_auto_20210828_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='descripción_personal',
            new_name='descripcion_personal',
        ),
    ]
