# Generated by Django 3.0.5 on 2021-09-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0009_rename_descripción_personal_equipo_descripcion_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
