# Generated by Django 3.0.5 on 2021-08-16 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_chaco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='modify',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='opcion1',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='opcion2',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='opcion3',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='opcion4',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='title',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='titulo',
            field=models.TextField(null=True, verbose_name='texto de pregunta'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False, verbose_name='¿Es esta la pregunta correcta?')),
                ('titulo', models.TextField(verbose_name='Texto de la respuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta', to='quiz_chaco.Pregunta')),
            ],
        ),
    ]
