# Generated by Django 3.0.5 on 2021-08-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_chaco', '0003_intentos_respuesta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Puntaje total'),
        ),
    ]
