# Generated by Django 3.0.5 on 2021-08-17 01:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_chaco', '0004_auto_20210816_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='perfilUsuario',
        ),
    ]
