# Generated by Django 3.2.6 on 2021-08-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_chaco', '0007_auto_20210817_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentos_respuesta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
